# Generated by Django 4.0.3 on 2022-03-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LIST_PIECES',
            fields=[
                ('RefOF', models.IntegerField(primary_key=True, serialize=False)),
                ('NumOF', models.IntegerField()),
                ('Qte', models.IntegerField()),
                ('Designation', models.CharField(max_length=100)),
                ('matiere', models.CharField(max_length=100)),
                ('Dimension', models.IntegerField()),
                ('Qualification', models.CharField(max_length=100)),
                ('Temps_Pre', models.IntegerField()),
                ('Temps_Rea', models.IntegerField()),
                ('TotalCNC_Pre', models.IntegerField()),
                ('TotalCNC_Rea', models.IntegerField()),
                ('TotalCONV_Pre', models.IntegerField()),
                ('TotalCONV_Rea', models.IntegerField()),
                ('Conformite_C', models.IntegerField()),
                ('Cnformite_NC', models.IntegerField()),
            ],
        ),
    ]
