# Generated by Django 4.0.2 on 2022-03-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListPieces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list_pieces',
            name='RefOF',
        ),
        migrations.AlterField(
            model_name='list_pieces',
            name='Conformité_C',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='list_pieces',
            name='Conformité_NC',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='list_pieces',
            name='Dimension',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='list_pieces',
            name='NumOF',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='list_pieces',
            name='Prévu_h',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='list_pieces',
            name='Qte',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='list_pieces',
            name='Réalisé_h',
            field=models.CharField(max_length=100),
        ),
    ]
