# Generated by Django 4.0.3 on 2022-03-14 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ListPieces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list_pieces',
            old_name='matiere',
            new_name='Matiere',
        ),
    ]
