# Generated by Django 4.0.3 on 2022-03-14 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ListPieces', '0002_rename_matiere_list_pieces_matiere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list_pieces',
            old_name='Cnformite_NC',
            new_name='Conformite_NC',
        ),
    ]
