# Generated by Django 4.0.3 on 2022-03-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OF',
            fields=[
                ('RefPr', models.IntegerField(primary_key=True, serialize=False)),
                ('NomPr', models.CharField(max_length=100)),
                ('StatutPr', models.CharField(max_length=100)),
                ('NumOF', models.IntegerField(max_length=100)),
                ('Priorité', models.CharField(max_length=100)),
            ],
        ),
    ]
