# Generated by Django 4.0.3 on 2022-03-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followUP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='of',
            name='NumOF',
            field=models.IntegerField(),
        ),
    ]
