# Generated by Django 4.0.3 on 2022-03-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followUP', '0002_alter_of_numof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='of',
            name='Priorité',
            field=models.IntegerField(),
        ),
    ]
