# Generated by Django 4.0.2 on 2022-03-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followUP', '0003_alter_of_priorité'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='of',
            name='NumOF',
        ),
        migrations.RemoveField(
            model_name='of',
            name='Priorité',
        ),
        migrations.AlterField(
            model_name='of',
            name='NomPr',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='of',
            name='StatutPr',
            field=models.CharField(default='', max_length=100),
        ),
    ]
