# Generated by Django 4.0.2 on 2022-03-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followUP', '0004_remove_of_numof_remove_of_priorité_alter_of_nompr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='of',
            name='NumOF',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='of',
            name='Priorité',
            field=models.CharField(default='', max_length=100),
        ),
    ]
