# Generated by Django 4.0.2 on 2022-03-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followUP', '0005_of_numof_of_priorité'),
    ]

    operations = [
        migrations.AlterField(
            model_name='of',
            name='NomPr',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='of',
            name='NumOF',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='of',
            name='Priorité',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='of',
            name='StatutPr',
            field=models.CharField(max_length=100),
        ),
    ]
