# Generated by Django 4.0.2 on 2022-03-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followUP', '0008_alter_of_nompr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='of',
            name='NomPr',
            field=models.CharField(default='', max_length=100),
        ),
    ]
